
kind: pipeline
name: default

steps:
  - name: run-test-cases
    image: cypress/base
    when:
      status:
      - failure
      - success
    commands:
      - npm install
      - npm test
  - name: result
    image: node
    when:
      status:
      - failure
      - success
    commands:
      - cat mochawesome-report/mochawesome.json
      
